//! Where a cached secret's value comes from, and how it can be regenerated.
//!
//! A cache entry's value originates from one of two kinds of [`ValueSource`]:
//!
//! - [`ValueSource::Static`]: a value supplied directly at `set` time. Once it
//!   reaches its hard TTL and is destroyed, it **cannot** be regenerated — the
//!   caller must `set` it again.
//! - [`ValueSource::Command`]: the output of an upstream command (e.g.
//!   `op read ...`). After hard expiry it **can** be regenerated by re-running
//!   the command.
//!
//! Command execution is delegated to a [`SourceRunner`] so that callers may
//! substitute a fake in tests and so the policy of *where* a process is spawned
//! stays explicit. The production runner is [`CommandRunner`].

use std::io::Read;
use std::process::{Command, Stdio};
use std::sync::mpsc;
use std::thread;
use std::time::{Duration, Instant};

use zeroize::Zeroize;

use crate::secret::SecretBytes;

/// The origin of a cached secret's value.
///
/// Holds enough information to describe *how* a value was obtained and whether
/// it can be regenerated, without holding the secret value itself.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ValueSource {
    /// A value provided directly at `set` time. Not regenerable after hard expiry.
    Static,
    /// The output of an upstream command. Regenerable by re-running `command`.
    Command {
        /// The command line to run to (re)produce the value, as already-split
        /// argv. The first element is the program; the rest are arguments.
        argv: Vec<String>,
    },
}

impl ValueSource {
    /// Construct a [`ValueSource::Command`] from an argv vector.
    pub fn command(argv: impl IntoIterator<Item = String>) -> Self {
        ValueSource::Command {
            argv: argv.into_iter().collect(),
        }
    }

    /// Whether this source can regenerate its value after hard expiry.
    ///
    /// `true` for [`ValueSource::Command`] (re-run the command), `false` for
    /// [`ValueSource::Static`] (the original value is gone; a re-`set` is needed).
    pub fn is_regenerable(&self) -> bool {
        matches!(self, ValueSource::Command { .. })
    }

    /// The argv to run for a [`ValueSource::Command`], or `None` for `Static`.
    pub fn command_argv(&self) -> Option<&[String]> {
        match self {
            ValueSource::Command { argv } => Some(argv),
            ValueSource::Static => None,
        }
    }
}

/// How [`CommandRunner`] treats a trailing newline on the command's stdout.
///
/// # Design rationale
///
/// Secret-emitting CLIs disagree on whether they append a newline. `op read`
/// prints `<value>\n`; a `printf '%s'` pipeline prints exactly the bytes. If we
/// kept the raw bytes, a cached `op read` token would carry a stray `\n` that
/// breaks string comparisons and header injection downstream. If we always
/// stripped, a value whose *legitimate* content ends in `\n` (rare, but e.g. a
/// PEM blob) would be silently corrupted.
///
/// We make it a policy with a safe default rather than hard-coding either
/// behavior: [`TrailingNewline::TrimOne`] removes at most **one** trailing
/// line terminator (`\n` or `\r\n`), matching the common "CLI adds one newline"
/// convention without chewing through intentional trailing blank lines. The
/// `Keep` variant preserves the bytes verbatim for callers who must.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum TrailingNewline {
    /// Strip a single trailing `\n` (and a preceding `\r`, if present). Default.
    #[default]
    TrimOne,
    /// Keep stdout exactly as produced, including any trailing newline.
    Keep,
}

impl TrailingNewline {
    /// Apply the policy in place to a stdout buffer.
    fn apply(self, buf: &mut Vec<u8>) {
        if self == TrailingNewline::TrimOne && buf.last() == Some(&b'\n') {
            buf.pop();
            if buf.last() == Some(&b'\r') {
                buf.pop();
            }
        }
    }
}

/// Error returned when running a [`ValueSource::Command`] fails.
///
/// # Redaction
///
/// The command's stderr is **never** transcribed into these errors. A failing
/// secret-fetch command may print partial secret material, prompts, or token
/// fragments to stderr; copying that into an error message (which is logged,
/// surfaced to users, and may end up in `Debug` output) would defeat the whole
/// point of the cache. We only report *that* stderr was produced and its byte
/// length, never its contents.
#[derive(Debug, PartialEq, Eq)]
pub enum RunError {
    /// The process could not be started (program not found, permission denied).
    SpawnFailed {
        /// The program name that failed to launch.
        program: String,
        /// OS-level reason (e.g. "No such file or directory"). Does not contain
        /// command output.
        reason: String,
    },
    /// The command ran but exited non-zero.
    NonZeroExit {
        /// The exit code, or `None` if terminated by a signal.
        code: Option<i32>,
        /// Number of bytes the command wrote to stderr (contents redacted).
        stderr_len: usize,
    },
    /// The command succeeded (exit 0) but produced no output, so there is no
    /// secret to cache.
    EmptyOutput,
    /// An empty argv was supplied; there is no program to run.
    NoProgram,
    /// The command did not finish within the configured timeout and was killed.
    ///
    /// Any partial stdout captured before the kill has already been zeroized.
    Timeout {
        /// How long the runner waited before killing the process.
        elapsed: Duration,
    },
}

impl std::fmt::Display for RunError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            RunError::SpawnFailed { program, reason } => {
                write!(f, "failed to spawn `{program}`: {reason}")
            }
            RunError::NonZeroExit { code, stderr_len } => match code {
                Some(c) => write!(
                    f,
                    "source command exited with status {c} ({stderr_len} bytes of stderr, redacted)"
                ),
                None => write!(
                    f,
                    "source command terminated by signal ({stderr_len} bytes of stderr, redacted)"
                ),
            },
            RunError::EmptyOutput => write!(f, "source command produced no output"),
            RunError::NoProgram => write!(f, "source command has no program (empty argv)"),
            RunError::Timeout { elapsed } => write!(
                f,
                "source command timed out after {elapsed:?} and was killed"
            ),
        }
    }
}

impl std::error::Error for RunError {}

/// Executes the command of a [`ValueSource::Command`] to (re)produce a secret.
///
/// Kept as a trait so the [`crate::Store`] never spawns processes directly and
/// so tests can substitute a fake. The production implementation is
/// [`CommandRunner`].
pub trait SourceRunner {
    /// Run `argv` and capture its stdout as a secret value.
    fn run(&self, argv: &[String]) -> Result<SecretBytes, RunError>;
}

/// Runs a source command with [`std::process::Command`] and captures stdout.
///
/// # Behavior
///
/// - The first argv element is the program; the rest are arguments.
/// - stdout is captured, the configured [`TrailingNewline`] policy is applied,
///   and the result is wrapped in a [`SecretBytes`].
/// - A non-zero exit, an empty argv, or a spawn failure are reported as the
///   corresponding [`RunError`] variants. An empty stdout on success is
///   [`RunError::EmptyOutput`] (there is nothing to cache).
/// - stderr contents are never copied into errors (see [`RunError`]).
///
/// # Secret hygiene
///
/// Stdout is read into an owned `Vec<u8>` (there is no zero-copy capture in
/// std). We move those bytes into a [`SecretBytes`] as the very next step on the
/// success path and [`Zeroize`] the intermediate buffer on every error path
/// where stdout was read (non-zero exit, timeout) — so plaintext never lingers
/// in a non-zeroizing buffer.
///
/// # Timeout policy (default: unlimited)
///
/// A timeout is **opt-in** via [`CommandRunner::with_timeout`]; the default
/// runner waits indefinitely.
///
/// Design rationale: a secret-fetch command often *legitimately* blocks for a
/// long time on user interaction — a TouchID / `op` prompt waits for the human
/// to authenticate, and there is no upper bound on how long that takes. A hard
/// default timeout would kill exactly the prompts we depend on, so the safe
/// default is "no timeout". Deployments that drive non-interactive sources (and
/// therefore *can* bound the runtime) opt in to a timeout to defend against a
/// genuinely hung command.
///
/// When a timeout is set and exceeded, the child is killed (and reaped to avoid
/// a zombie), any partial stdout is zeroized, and [`RunError::Timeout`] is
/// returned.
#[derive(Debug, Clone, Copy, Default)]
pub struct CommandRunner {
    newline: TrailingNewline,
    /// Maximum wall-clock time to wait for the command, or `None` for unlimited.
    timeout: Option<Duration>,
}

impl CommandRunner {
    /// A runner using the default newline policy ([`TrailingNewline::TrimOne`])
    /// and no timeout.
    pub fn new() -> Self {
        Self::default()
    }

    /// A runner with an explicit trailing-newline policy (no timeout).
    pub fn with_newline_policy(newline: TrailingNewline) -> Self {
        Self {
            newline,
            timeout: None,
        }
    }

    /// Return a runner that kills the command if it runs longer than `timeout`.
    ///
    /// See the type-level "Timeout policy" note for why this is opt-in. Combine
    /// with [`CommandRunner::with_newline_policy`] via the builder style:
    /// `CommandRunner::new().with_timeout(d)`.
    pub fn with_timeout(self, timeout: Duration) -> Self {
        Self {
            timeout: Some(timeout),
            ..self
        }
    }

    /// Spawn the child and collect stdout + stderr, enforcing a timeout if set.
    ///
    /// Both streams are drained on dedicated threads so a child that fills an OS
    /// pipe buffer cannot deadlock us, and so the timeout can fire even while
    /// output is pending. Returns `(stdout, stderr_len, status)`; stderr
    /// *contents* are never surfaced (see [`RunError`]), only its byte length.
    fn collect(
        &self,
        program: &str,
        args: &[String],
    ) -> Result<(Vec<u8>, usize, std::process::ExitStatus), RunError> {
        let mut child = Command::new(program)
            .args(args)
            .stdin(Stdio::null())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .map_err(|e| RunError::SpawnFailed {
                program: program.to_string(),
                reason: e.to_string(),
            })?;

        // Drain both pipes on reader threads: a full pipe must never block us,
        // and the threads let the main path poll the child for the timeout.
        let mut stdout_pipe = child.stdout.take().expect("stdout was piped");
        let mut stderr_pipe = child.stderr.take().expect("stderr was piped");
        let (out_tx, out_rx) = mpsc::channel();
        let out_reader = thread::spawn(move || {
            let mut buf = Vec::new();
            let _ = stdout_pipe.read_to_end(&mut buf);
            let _ = out_tx.send(buf);
        });
        let (err_tx, err_rx) = mpsc::channel();
        let err_reader = thread::spawn(move || {
            let mut buf = Vec::new();
            let _ = stderr_pipe.read_to_end(&mut buf);
            let _ = err_tx.send(buf.len());
        });
        let drains = Drains {
            out_rx,
            out_reader,
            err_rx,
            err_reader,
        };

        match self.timeout {
            None => {
                let status = child.wait().map_err(|e| RunError::SpawnFailed {
                    program: program.to_string(),
                    reason: e.to_string(),
                })?;
                let (stdout, stderr_len) = drains.collect();
                Ok((stdout, stderr_len, status))
            }
            Some(limit) => self.wait_with_timeout(child, drains, limit, program),
        }
    }

    /// Poll the child until it exits or `limit` elapses, killing on timeout.
    fn wait_with_timeout(
        &self,
        mut child: std::process::Child,
        drains: Drains,
        limit: Duration,
        program: &str,
    ) -> Result<(Vec<u8>, usize, std::process::ExitStatus), RunError> {
        let start = Instant::now();
        // Poll with a short, bounded interval: responsive without busy-spinning.
        let poll = Duration::from_millis(10).min(limit);
        loop {
            match child.try_wait() {
                Ok(Some(status)) => {
                    let (stdout, stderr_len) = drains.collect();
                    return Ok((stdout, stderr_len, status));
                }
                Ok(None) => {
                    if start.elapsed() >= limit {
                        // Kill, then reap so we do not leave a zombie.
                        let _ = child.kill();
                        let _ = child.wait();
                        // Wipe any partial stdout the reader managed to collect.
                        let (mut partial, _) = drains.collect();
                        partial.zeroize();
                        return Err(RunError::Timeout {
                            elapsed: start.elapsed(),
                        });
                    }
                    thread::sleep(poll);
                }
                Err(e) => {
                    let _ = child.kill();
                    let _ = child.wait();
                    return Err(RunError::SpawnFailed {
                        program: program.to_string(),
                        reason: e.to_string(),
                    });
                }
            }
        }
    }
}

/// The drain channels + reader threads for a spawned child's stdout/stderr.
struct Drains {
    out_rx: mpsc::Receiver<Vec<u8>>,
    out_reader: thread::JoinHandle<()>,
    err_rx: mpsc::Receiver<usize>,
    err_reader: thread::JoinHandle<()>,
}

impl Drains {
    /// Receive the drained stdout bytes + stderr length and join both threads.
    fn collect(self) -> (Vec<u8>, usize) {
        let stdout = self.out_rx.recv().unwrap_or_default();
        let stderr_len = self.err_rx.recv().unwrap_or(0);
        let _ = self.out_reader.join();
        let _ = self.err_reader.join();
        (stdout, stderr_len)
    }
}

impl SourceRunner for CommandRunner {
    fn run(&self, argv: &[String]) -> Result<SecretBytes, RunError> {
        let (program, args) = argv.split_first().ok_or(RunError::NoProgram)?;

        let (mut stdout, stderr_len, status) = self.collect(program, args)?;

        if !status.success() {
            // stdout may hold partial secret material even on failure — wipe it.
            stdout.zeroize();
            return Err(RunError::NonZeroExit {
                code: status.code(),
                stderr_len,
            });
        }

        self.newline.apply(&mut stdout);

        if stdout.is_empty() {
            return Err(RunError::EmptyOutput);
        }

        // Move the plaintext buffer into the zeroizing holder without copying;
        // no intermediate plaintext copy is ever made on the success path.
        Ok(SecretBytes::new(std::mem::take(&mut stdout)))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn static_is_not_regenerable() {
        let s = ValueSource::Static;
        assert!(!s.is_regenerable());
        assert_eq!(s.command_argv(), None);
    }

    #[test]
    fn command_is_regenerable() {
        let s = ValueSource::command(["op".to_string(), "read".to_string()]);
        assert!(s.is_regenerable());
        assert_eq!(
            s.command_argv(),
            Some(["op".to_string(), "read".to_string()].as_slice())
        );
    }

    /// A fake runner so tests can exercise regeneration without spawning processes.
    struct FixedRunner(Vec<u8>);
    impl SourceRunner for FixedRunner {
        fn run(&self, _argv: &[String]) -> Result<SecretBytes, RunError> {
            Ok(SecretBytes::new(self.0.clone()))
        }
    }

    #[test]
    fn fake_runner_produces_secret() {
        let runner = FixedRunner(b"regenerated".to_vec());
        let out = runner.run(&["op".to_string()]).unwrap();
        assert_eq!(out.expose_secret(), b"regenerated");
    }

    // ---- RunError display ----

    #[test]
    fn run_error_nonzero_displays_code_and_redacts_stderr() {
        let e = RunError::NonZeroExit {
            code: Some(1),
            stderr_len: 42,
        };
        let s = e.to_string();
        assert!(s.contains("status 1"));
        assert!(s.contains("redacted"));
        assert!(s.contains("42"));
    }

    #[test]
    fn run_error_spawn_failed_displays_program() {
        let e = RunError::SpawnFailed {
            program: "no-such-bin".into(),
            reason: "not found".into(),
        };
        assert!(e.to_string().contains("no-such-bin"));
    }

    // ---- TrailingNewline policy (unit) ----

    #[test]
    fn trim_one_removes_single_lf() {
        let mut b = b"value\n".to_vec();
        TrailingNewline::TrimOne.apply(&mut b);
        assert_eq!(b, b"value");
    }

    #[test]
    fn trim_one_removes_crlf() {
        let mut b = b"value\r\n".to_vec();
        TrailingNewline::TrimOne.apply(&mut b);
        assert_eq!(b, b"value");
    }

    #[test]
    fn trim_one_keeps_internal_and_extra_trailing_newlines() {
        let mut b = b"a\nb\n\n".to_vec();
        TrailingNewline::TrimOne.apply(&mut b);
        // Only one trailing newline removed.
        assert_eq!(b, b"a\nb\n");
    }

    #[test]
    fn keep_preserves_newline() {
        let mut b = b"value\n".to_vec();
        TrailingNewline::Keep.apply(&mut b);
        assert_eq!(b, b"value\n");
    }

    // ---- CommandRunner against real commands (macOS-available binaries) ----

    fn argv(parts: &[&str]) -> Vec<String> {
        parts.iter().map(|s| s.to_string()).collect()
    }

    #[test]
    fn command_runner_captures_stdout_and_trims_newline() {
        // `echo` appends a trailing newline; default policy trims exactly one.
        let r = CommandRunner::new();
        let out = r.run(&argv(&["echo", "hunter2"])).unwrap();
        assert_eq!(out.expose_secret(), b"hunter2");
    }

    #[test]
    fn command_runner_keep_policy_preserves_newline() {
        let r = CommandRunner::with_newline_policy(TrailingNewline::Keep);
        let out = r.run(&argv(&["echo", "hunter2"])).unwrap();
        assert_eq!(out.expose_secret(), b"hunter2\n");
    }

    #[test]
    fn command_runner_captures_value_without_trailing_newline() {
        // `printf '%s'` emits no trailing newline; the value is captured verbatim.
        let r = CommandRunner::new();
        let out = r.run(&argv(&["printf", "%s", "raw-token"])).unwrap();
        assert_eq!(out.expose_secret(), b"raw-token");
    }

    #[test]
    fn command_runner_nonzero_exit_is_classified() {
        let r = CommandRunner::new();
        let err = r.run(&argv(&["false"])).unwrap_err();
        assert!(matches!(
            err,
            RunError::NonZeroExit {
                code: Some(c),
                ..
            } if c != 0
        ));
    }

    #[test]
    fn command_runner_empty_stdout_is_empty_output() {
        // `true` succeeds with no output -> nothing to cache.
        let r = CommandRunner::new();
        let err = r.run(&argv(&["true"])).unwrap_err();
        assert_eq!(err, RunError::EmptyOutput);
    }

    #[test]
    fn command_runner_value_that_is_only_a_newline_is_empty_after_trim() {
        // A command that prints just "\n" trims to empty -> EmptyOutput.
        let r = CommandRunner::new();
        let err = r.run(&argv(&["echo"])).unwrap_err();
        assert_eq!(err, RunError::EmptyOutput);
    }

    #[test]
    fn command_runner_spawn_failure_is_classified() {
        let r = CommandRunner::new();
        let err = r
            .run(&argv(&["this-binary-does-not-exist-cache-warden"]))
            .unwrap_err();
        assert!(matches!(err, RunError::SpawnFailed { .. }));
    }

    #[test]
    fn command_runner_empty_argv_is_no_program() {
        let r = CommandRunner::new();
        let err = r.run(&[]).unwrap_err();
        assert_eq!(err, RunError::NoProgram);
    }

    #[test]
    fn command_runner_stderr_is_not_in_error_contents() {
        // sh writes a secret-looking string to stderr and exits non-zero.
        let r = CommandRunner::new();
        let err = r
            .run(&argv(&[
                "sh",
                "-c",
                "echo LEAKED_SECRET_abc123 >&2; exit 3",
            ]))
            .unwrap_err();
        match &err {
            RunError::NonZeroExit { code, stderr_len } => {
                assert_eq!(*code, Some(3));
                assert!(*stderr_len > 0);
            }
            other => panic!("unexpected: {other:?}"),
        }
        // The error's Display must not contain the stderr payload.
        assert!(!err.to_string().contains("LEAKED_SECRET"));
    }

    #[test]
    fn command_runner_captures_multiline_secret_via_sh() {
        // A value with internal newlines (PEM-like) keeps its interior, loses one trailing.
        let r = CommandRunner::new();
        let out = r.run(&argv(&["printf", "line1\nline2\n"])).unwrap();
        assert_eq!(out.expose_secret(), b"line1\nline2");
    }

    // ---- timeout ----

    #[test]
    fn run_error_timeout_displays_elapsed_and_redacts() {
        let e = RunError::Timeout {
            elapsed: Duration::from_millis(250),
        };
        let s = e.to_string();
        assert!(s.contains("timed out"));
        assert!(s.contains("killed"));
    }

    #[test]
    fn command_runner_kills_command_that_exceeds_timeout() {
        // `sleep 5` would normally block the caller for 5s; with a 200ms timeout
        // the runner kills it and reports Timeout well before then.
        let r = CommandRunner::new().with_timeout(Duration::from_millis(200));
        let start = Instant::now();
        let err = r.run(&argv(&["sleep", "5"])).unwrap_err();
        let waited = start.elapsed();
        match err {
            RunError::Timeout { elapsed } => {
                assert!(elapsed >= Duration::from_millis(200));
            }
            other => panic!("expected Timeout, got {other:?}"),
        }
        // We must not have waited anywhere near the full 5s.
        assert!(
            waited < Duration::from_secs(2),
            "runner should return shortly after the timeout, waited {waited:?}"
        );
    }

    #[test]
    fn command_runner_fast_command_succeeds_under_timeout() {
        // A command that finishes well within the timeout returns its value
        // normally — the timeout only fires on genuinely slow commands.
        let r = CommandRunner::new().with_timeout(Duration::from_secs(5));
        let out = r.run(&argv(&["echo", "quick"])).unwrap();
        assert_eq!(out.expose_secret(), b"quick");
    }

    #[test]
    fn command_runner_no_timeout_still_works() {
        // The default (unlimited) runner is unchanged by the timeout plumbing.
        let r = CommandRunner::new();
        let out = r.run(&argv(&["echo", "ok"])).unwrap();
        assert_eq!(out.expose_secret(), b"ok");
    }

    #[test]
    fn command_runner_captures_large_stdout_without_pipe_deadlock() {
        // A large payload would deadlock a naive "wait then read" implementation
        // because the OS pipe buffer fills before the child exits. The reader
        // thread drains it concurrently. `head -c` caps the stream at 256 KiB,
        // far larger than any pipe buffer (typically 64 KiB).
        let r = CommandRunner::new().with_timeout(Duration::from_secs(10));
        let out = r
            .run(&argv(&[
                "sh",
                "-c",
                "head -c 262144 /dev/zero | tr '\\0' x",
            ]))
            .unwrap();
        assert_eq!(out.len(), 262144);
    }
}
