//! Where a cached secret's value comes from, and how it can be regenerated.
//!
//! A cache entry's value originates from one of two kinds of [`ValueSource`]:
//!
//! - [`ValueSource::Static`]: a value supplied directly at `set` time. Once it
//!   reaches its hard TTL and is destroyed, it **cannot** be regenerated — the
//!   caller must `set` it again.
//! - [`ValueSource::Command`]: the output of an upstream command (e.g.
//!   `op read ...`). After hard expiry it **can** be regenerated by re-running
//!   the command.
//!
//! The command is not executed inside the core. Execution is delegated to a
//! [`SourceRunner`] so that the domain core stays pure and free of process /
//! IO concerns. The real runner is implemented in a later iteration.

use crate::secret::SecretBytes;

/// The origin of a cached secret's value.
///
/// Holds enough information to describe *how* a value was obtained and whether
/// it can be regenerated, without holding the secret value itself.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ValueSource {
    /// A value provided directly at `set` time. Not regenerable after hard expiry.
    Static,
    /// The output of an upstream command. Regenerable by re-running `command`.
    Command {
        /// The command line to run to (re)produce the value, as already-split
        /// argv. The first element is the program; the rest are arguments.
        argv: Vec<String>,
    },
}

impl ValueSource {
    /// Construct a [`ValueSource::Command`] from an argv vector.
    pub fn command(argv: impl IntoIterator<Item = String>) -> Self {
        ValueSource::Command {
            argv: argv.into_iter().collect(),
        }
    }

    /// Whether this source can regenerate its value after hard expiry.
    ///
    /// `true` for [`ValueSource::Command`] (re-run the command), `false` for
    /// [`ValueSource::Static`] (the original value is gone; a re-`set` is needed).
    pub fn is_regenerable(&self) -> bool {
        matches!(self, ValueSource::Command { .. })
    }

    /// The argv to run for a [`ValueSource::Command`], or `None` for `Static`.
    pub fn command_argv(&self) -> Option<&[String]> {
        match self {
            ValueSource::Command { argv } => Some(argv),
            ValueSource::Static => None,
        }
    }
}

/// Error returned when running a [`ValueSource::Command`] fails.
#[derive(Debug)]
pub struct RunError {
    /// Human-readable failure description.
    pub message: String,
}

impl RunError {
    /// Create a [`RunError`] with the given message.
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
        }
    }
}

impl std::fmt::Display for RunError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "source command failed: {}", self.message)
    }
}

impl std::error::Error for RunError {}

/// Executes the command of a [`ValueSource::Command`] to (re)produce a secret.
///
/// Kept as a trait so the core never spawns processes directly; the production
/// implementation lives outside the pure domain core (later iteration).
pub trait SourceRunner {
    /// Run `argv` and capture its output as a secret value.
    fn run(&self, argv: &[String]) -> Result<SecretBytes, RunError>;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn static_is_not_regenerable() {
        let s = ValueSource::Static;
        assert!(!s.is_regenerable());
        assert_eq!(s.command_argv(), None);
    }

    #[test]
    fn command_is_regenerable() {
        let s = ValueSource::command(["op".to_string(), "read".to_string()]);
        assert!(s.is_regenerable());
        assert_eq!(
            s.command_argv(),
            Some(["op".to_string(), "read".to_string()].as_slice())
        );
    }

    /// A fake runner so tests can exercise regeneration without spawning processes.
    struct FixedRunner(Vec<u8>);
    impl SourceRunner for FixedRunner {
        fn run(&self, _argv: &[String]) -> Result<SecretBytes, RunError> {
            Ok(SecretBytes::new(self.0.clone()))
        }
    }

    #[test]
    fn runner_produces_secret() {
        let runner = FixedRunner(b"regenerated".to_vec());
        let out = runner.run(&["op".to_string()]).unwrap();
        assert_eq!(out.expose_secret(), b"regenerated");
    }

    #[test]
    fn run_error_displays_message() {
        let e = RunError::new("exit code 1");
        assert!(e.to_string().contains("exit code 1"));
    }
}
