//! Per-user service registration backends (`daemon register / unregister /
//! status`) for launchd (macOS) and `systemd --user` (Linux) — DR-0019.
//!
//! The two OSes map to one CLI by staying **per-user** (LaunchAgents ≈
//! `systemd --user`): start command, auto-start, restart, env, and log target
//! all have a 1:1 counterpart (DR-0019 §2).
//!
//! # Layering
//!
//! - [`ServiceDefinition`] is the OS-neutral description (label, argv, env, log
//!   path). It is built once by [`ServiceDefinition::for_daemon`] and fed to
//!   both renderers.
//! - [`render_launchd_plist`] / [`render_systemd_unit`] are **pure** functions
//!   (plist XML / unit ini as a string, escaping included). They are compiled on
//!   every platform so their golden tests run on macOS *and* Linux — only the
//!   live `launchctl` / `systemctl` shell-out is `cfg`-gated.
//! - [`Backend`] hides the OS service manager; [`backend`] selects the live one,
//!   returning an `unsupported platform` error elsewhere.
//!
//! Design rationale: the plist/unit text is generated by hand (template +
//! escaping) rather than via an XML/ini crate. DR-0002 keeps the dependency
//! surface minimal; the documents are tiny and fixed-shape, so hand-rolled
//! escaping (with golden tests) is cheaper than a serializer dependency.

use std::collections::BTreeMap;
use std::path::PathBuf;

/// The OS-neutral description of the daemon service to register (DR-0019 §2).
///
/// The same struct drives both the launchd plist and the systemd unit; the
/// renderers pick the fields each format needs.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ServiceDefinition {
    /// The service label / unit name. launchd: the plist `Label` and file
    /// basename; systemd: the unit basename. Defaults differ per OS
    /// ([`default_label`]).
    pub label: String,
    /// The full start command: the daemon binary's absolute path followed by
    /// `daemon run [--socket PATH]` (DR-0019 §2). Never empty.
    pub program_args: Vec<String>,
    /// Environment variables baked into the service definition: `CACHE_WARDEN_CONFIG`
    /// (the register-time resolved config path, DR-0019 §2) and a minimal `PATH`
    /// so `op` is found. Sorted for deterministic output.
    pub env: BTreeMap<String, String>,
    /// launchd-only: the combined stdout/stderr log path
    /// (`~/Library/Logs/cache-warden/daemon.log`). systemd uses journald and
    /// ignores this (DR-0019 §2).
    pub log_path: Option<String>,
}

/// The default per-user service label for the current OS (DR-0019 §1):
/// `com.github.kawaz.cache-warden` on macOS (reverse-DNS launchd convention),
/// `cache-warden` on Linux (systemd unit name).
pub fn default_label() -> &'static str {
    if cfg!(target_os = "macos") {
        "com.github.kawaz.cache-warden"
    } else {
        "cache-warden"
    }
}

/// A minimal PATH baked into the service definition so the daemon can find
/// `op` (and friends) without inheriting the user's session-specific PATH
/// (DR-0019 §2: avoid the warden plist's session-path mistake).
const SERVICE_PATH: &str =
    "/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin";

impl ServiceDefinition {
    /// Build the daemon service definition (DR-0019 §2).
    ///
    /// - `exe`: the absolute path of the running binary (`current_exe()`), used
    ///   verbatim as `ProgramArguments[0]` / `ExecStart`.
    /// - `label`: the service label (`--label` or the per-OS default).
    /// - `socket`: when set, appended as `--socket PATH` so the service binds the
    ///   same control socket the operator chose at register time.
    /// - `config_path`: the register-time resolved config file path. When `Some`,
    ///   baked in as `CACHE_WARDEN_CONFIG` so the service does not silently pick up
    ///   a *different* config than the one in effect at register time (DR-0019 §2:
    ///   explicit beats implicit). `None` (no config file exists) bakes nothing —
    ///   the daemon runs all-defaults.
    /// - `log_path`: launchd log target (ignored by systemd).
    pub fn for_daemon(
        exe: &str,
        label: &str,
        socket: Option<&str>,
        config_path: Option<&str>,
        log_path: Option<String>,
    ) -> Self {
        let mut program_args = vec![exe.to_string(), "daemon".to_string(), "run".to_string()];
        if let Some(s) = socket {
            program_args.push("--socket".to_string());
            program_args.push(s.to_string());
        }
        let mut env = BTreeMap::new();
        if let Some(cfg) = config_path {
            env.insert("CACHE_WARDEN_CONFIG".to_string(), cfg.to_string());
        }
        env.insert("PATH".to_string(), SERVICE_PATH.to_string());
        ServiceDefinition {
            label: label.to_string(),
            program_args,
            env,
            log_path,
        }
    }
}

// ---- launchd plist (pure render) ---------------------------------------

/// Escape a string for an XML text node / attribute value (`&`, `<`, `>`).
///
/// Quotes are left as-is: the values only ever land in element text, never an
/// attribute, so `<` `>` `&` are the only metacharacters that can break the
/// document. Order matters — `&` must be replaced first.
fn xml_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

/// Render the launchd LaunchAgent plist for `def` (DR-0019 §2), as an XML
/// document string.
///
/// `KeepAlive` (restart) + `RunAtLoad` (auto-start) mirror the systemd
/// `Restart=on-failure` + `WantedBy=default.target`. All interpolated values are
/// XML-escaped.
///
/// Design rationale: compiled on every platform so the golden test runs on Linux
/// CI too (DR-0019 §4); the live launchd backend that calls it is macOS-only.
#[cfg_attr(not(target_os = "macos"), allow(dead_code))]
pub fn render_launchd_plist(def: &ServiceDefinition) -> String {
    let mut out = String::new();
    out.push_str("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
    out.push_str(
        "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \
         \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n",
    );
    out.push_str("<plist version=\"1.0\">\n");
    out.push_str("<dict>\n");

    out.push_str("\t<key>Label</key>\n");
    out.push_str(&format!("\t<string>{}</string>\n", xml_escape(&def.label)));

    out.push_str("\t<key>ProgramArguments</key>\n");
    out.push_str("\t<array>\n");
    for arg in &def.program_args {
        out.push_str(&format!("\t\t<string>{}</string>\n", xml_escape(arg)));
    }
    out.push_str("\t</array>\n");

    out.push_str("\t<key>RunAtLoad</key>\n\t<true/>\n");
    out.push_str("\t<key>KeepAlive</key>\n\t<true/>\n");

    if !def.env.is_empty() {
        out.push_str("\t<key>EnvironmentVariables</key>\n");
        out.push_str("\t<dict>\n");
        for (k, v) in &def.env {
            out.push_str(&format!("\t\t<key>{}</key>\n", xml_escape(k)));
            out.push_str(&format!("\t\t<string>{}</string>\n", xml_escape(v)));
        }
        out.push_str("\t</dict>\n");
    }

    if let Some(log) = &def.log_path {
        let log = xml_escape(log);
        out.push_str("\t<key>StandardOutPath</key>\n");
        out.push_str(&format!("\t<string>{log}</string>\n"));
        out.push_str("\t<key>StandardErrorPath</key>\n");
        out.push_str(&format!("\t<string>{log}</string>\n"));
    }

    out.push_str("</dict>\n");
    out.push_str("</plist>\n");
    out
}

// ---- systemd unit (pure render) ----------------------------------------

/// Quote a value for a systemd `Environment=` assignment.
///
/// systemd splits `Environment=` on whitespace unless the whole `NAME=VALUE` is
/// double-quoted; inside the quotes `"` and `\` must be backslash-escaped. We
/// always emit the quoted form (`Environment="NAME=VALUE"`) so values containing
/// spaces, `=`, or quotes survive intact.
///
/// Design rationale: compiled on every platform (not behind `cfg(linux)`) so the
/// golden tests run on macOS too (DR-0019 §4); the `allow(dead_code)` covers the
/// non-Linux build where the live systemd backend is absent.
#[cfg_attr(not(target_os = "linux"), allow(dead_code))]
fn systemd_env_line(name: &str, value: &str) -> String {
    let escaped = value.replace('\\', "\\\\").replace('"', "\\\"");
    format!("Environment=\"{name}={escaped}\"\n")
}

/// Quote one `ExecStart` argument for systemd.
///
/// systemd's command-line parser splits on unquoted whitespace and honours
/// double quotes. Any argument containing whitespace, a quote, or a backslash is
/// emitted double-quoted with `"` / `\` escaped; simple arguments pass through
/// bare for readability.
///
/// Design rationale: compiled on every platform for the golden tests (DR-0019 §4).
#[cfg_attr(not(target_os = "linux"), allow(dead_code))]
fn systemd_exec_arg(arg: &str) -> String {
    let needs_quote = arg.is_empty()
        || arg
            .chars()
            .any(|c| c.is_whitespace() || c == '"' || c == '\\' || c == '\'');
    if needs_quote {
        let escaped = arg.replace('\\', "\\\\").replace('"', "\\\"");
        format!("\"{escaped}\"")
    } else {
        arg.to_string()
    }
}

/// Render the `systemd --user` service unit for `def` (DR-0019 §2), as an ini
/// document string.
///
/// `Restart=on-failure` (restart) + `WantedBy=default.target` (auto-start)
/// mirror launchd's `KeepAlive` + `RunAtLoad`. Logging goes to journald (no path
/// directive). `Environment=` lines are quoted per systemd's rules.
///
/// Design rationale: compiled on every platform so the golden test runs on macOS
/// and Linux alike (DR-0019 §4); the live systemd backend (which calls it) only
/// exists on Linux.
#[cfg_attr(not(target_os = "linux"), allow(dead_code))]
pub fn render_systemd_unit(def: &ServiceDefinition) -> String {
    let exec: Vec<String> = def
        .program_args
        .iter()
        .map(|a| systemd_exec_arg(a))
        .collect();

    let mut out = String::new();
    out.push_str("[Unit]\n");
    out.push_str("Description=cache-warden secret cache daemon (DR-0019)\n");
    out.push('\n');

    out.push_str("[Service]\n");
    out.push_str("Type=simple\n");
    out.push_str(&format!("ExecStart={}\n", exec.join(" ")));
    out.push_str("Restart=on-failure\n");
    // env is name-sorted (BTreeMap) → deterministic unit output.
    for (k, v) in &def.env {
        out.push_str(&systemd_env_line(k, v));
    }
    out.push('\n');

    out.push_str("[Install]\n");
    out.push_str("WantedBy=default.target\n");
    out
}

// ---- service status (OS-neutral shape) ---------------------------------

/// The OS-neutral registration state of the service (DR-0019 §1), rendered the
/// same way on both platforms by [`Backend::status`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ServiceStatus {
    /// Whether a service definition file is installed.
    pub registered: bool,
    /// Whether the service manager reports it currently running.
    pub running: bool,
    /// The running pid, if known.
    pub pid: Option<u32>,
    /// The definition file path (plist / unit), shown whether or not it exists.
    pub definition_path: PathBuf,
}

impl ServiceStatus {
    /// Render the status as a one-screen table (DR-0019 §1), the same layout on
    /// both OSes.
    pub fn render(&self, label: &str) -> String {
        let registered = if self.registered { "yes" } else { "no" };
        let running = if self.running { "yes" } else { "no" };
        let pid = self
            .pid
            .map(|p| p.to_string())
            .unwrap_or_else(|| "-".into());
        format!(
            "label:      {label}\n\
             registered: {registered}\n\
             running:    {running}\n\
             pid:        {pid}\n\
             definition: {}\n",
            self.definition_path.display()
        )
    }
}

// ---- backend trait + selection -----------------------------------------

/// A per-user service manager (launchd or systemd) abstracted behind one CLI
/// (DR-0019 §4). Implementations shell out to `launchctl` / `systemctl` (the op
/// shell-out policy — no FFI to the service-manager API).
pub trait Backend {
    /// The definition file path for `label` (plist / unit).
    fn definition_path(&self, label: &str) -> PathBuf;

    /// Render the OS-native definition for `def` (plist XML / unit ini).
    fn render_definition(&self, def: &ServiceDefinition) -> String;

    /// Write the definition and (re-)load the service so it starts now and at
    /// login. Idempotent: an existing registration is updated and restarted.
    fn register(&self, def: &ServiceDefinition) -> Result<(), String>;

    /// Stop, unload, and delete the definition for `label`. A no-op if not
    /// registered (idempotent).
    fn unregister(&self, label: &str) -> Result<(), String>;

    /// Report the registration / running state for `label`.
    fn status(&self, label: &str) -> Result<ServiceStatus, String>;
}

/// Select the live backend for this OS, or an `unsupported platform` error
/// (DR-0019 §4).
#[cfg(target_os = "macos")]
pub fn backend() -> Result<Box<dyn Backend>, String> {
    Ok(Box::new(launchd::LaunchdBackend))
}

/// Select the live backend for this OS, or an `unsupported platform` error.
#[cfg(target_os = "linux")]
pub fn backend() -> Result<Box<dyn Backend>, String> {
    Ok(Box::new(systemd::SystemdBackend))
}

/// Select the live backend for this OS, or an `unsupported platform` error.
#[cfg(not(any(target_os = "macos", target_os = "linux")))]
pub fn backend() -> Result<Box<dyn Backend>, String> {
    Err(
        "daemon register/unregister/status: unsupported platform (only macOS \
         launchd and Linux systemd --user are supported; DR-0019)"
            .to_string(),
    )
}

/// The default launchd log target: `~/Library/Logs/cache-warden/daemon.log`
/// (DR-0019 §2). `None` only if `$HOME` is unset.
pub fn default_log_path() -> Option<String> {
    std::env::var_os("HOME").map(|home| {
        PathBuf::from(home)
            .join("Library/Logs/cache-warden/daemon.log")
            .to_string_lossy()
            .into_owned()
    })
}

// ---- launchd live backend (macOS) --------------------------------------

#[cfg(target_os = "macos")]
pub mod launchd {
    use super::{Backend, ServiceDefinition, ServiceStatus, render_launchd_plist};
    use std::path::PathBuf;
    use std::process::Command;

    /// The launchd LaunchAgent backend: writes `~/Library/LaunchAgents/<label>.plist`
    /// and drives it with the modern `launchctl bootstrap/bootout` API (DR-0019 §1;
    /// the deprecated `load`/`unload` is avoided).
    pub struct LaunchdBackend;

    /// The current effective UID (the launchd `gui/$UID` domain target).
    fn uid() -> u32 {
        // SAFETY: getuid() is always-succeeds and thread-safe.
        unsafe { libc::getuid() }
    }

    impl LaunchdBackend {
        fn plist_path(label: &str) -> PathBuf {
            let home = std::env::var_os("HOME")
                .map(PathBuf::from)
                .unwrap_or_default();
            home.join("Library/LaunchAgents")
                .join(format!("{label}.plist"))
        }
    }

    impl Backend for LaunchdBackend {
        fn definition_path(&self, label: &str) -> PathBuf {
            Self::plist_path(label)
        }

        fn render_definition(&self, def: &ServiceDefinition) -> String {
            render_launchd_plist(def)
        }

        fn register(&self, def: &ServiceDefinition) -> Result<(), String> {
            let path = Self::plist_path(&def.label);
            if let Some(parent) = path.parent() {
                std::fs::create_dir_all(parent)
                    .map_err(|e| format!("cannot create {}: {e}", parent.display()))?;
            }
            // Ensure the log directory exists so launchd can open the log file.
            if let Some(log) = &def.log_path
                && let Some(parent) = std::path::Path::new(log).parent()
            {
                let _ = std::fs::create_dir_all(parent);
            }
            std::fs::write(&path, render_launchd_plist(def))
                .map_err(|e| format!("cannot write {}: {e}", path.display()))?;

            let domain = format!("gui/{}", uid());
            let target = format!("{domain}/{}", def.label);
            // Idempotent re-register: bootout any prior instance first, then
            // bootstrap the freshly-written plist. A fresh register has nothing
            // to bootout (`Boot-out failed: 3: No such process`), which is
            // expected — discard its output so the noise never reaches the user.
            let _ = Command::new("launchctl")
                .args(["bootout", &target])
                .output();
            let out = Command::new("launchctl")
                .args(["bootstrap", &domain])
                .arg(&path)
                .output()
                .map_err(|e| format!("failed to run launchctl bootstrap: {e}"))?;
            if !out.status.success() {
                return Err(format!(
                    "launchctl bootstrap failed: {}",
                    String::from_utf8_lossy(&out.stderr).trim()
                ));
            }
            Ok(())
        }

        fn unregister(&self, label: &str) -> Result<(), String> {
            let target = format!("gui/{}/{label}", uid());
            // bootout is best-effort: a not-loaded service is not an error here.
            // Use `output()` so the "No such process" message stays quiet.
            let _ = Command::new("launchctl")
                .args(["bootout", &target])
                .output();
            let path = Self::plist_path(label);
            match std::fs::remove_file(&path) {
                Ok(()) => Ok(()),
                Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
                Err(e) => Err(format!("cannot remove {}: {e}", path.display())),
            }
        }

        fn status(&self, label: &str) -> Result<ServiceStatus, String> {
            let path = Self::plist_path(label);
            let registered = path.is_file();
            let target = format!("gui/{}/{label}", uid());
            let out = Command::new("launchctl")
                .args(["print", &target])
                .output()
                .map_err(|e| format!("failed to run launchctl print: {e}"))?;
            // `launchctl print` exits non-zero when the service is not loaded.
            let (running, pid) = if out.status.success() {
                let text = String::from_utf8_lossy(&out.stdout);
                let pid = super::parse_launchctl_pid(&text);
                (pid.is_some(), pid)
            } else {
                (false, None)
            };
            Ok(ServiceStatus {
                registered,
                running,
                pid,
                definition_path: path,
            })
        }
    }
}

/// Parse the `pid = N` field from `launchctl print` output (DR-0019 §1). The
/// daemon is running iff a numeric pid is present. Pure so it is unit-testable
/// on any platform (hence compiled everywhere though only the macOS backend
/// calls it).
#[cfg_attr(not(target_os = "macos"), allow(dead_code))]
pub fn parse_launchctl_pid(text: &str) -> Option<u32> {
    for line in text.lines() {
        let line = line.trim();
        if let Some(rest) = line.strip_prefix("pid = ") {
            return rest.trim().parse().ok();
        }
    }
    None
}

// ---- systemd live backend (Linux) --------------------------------------

#[cfg(target_os = "linux")]
pub mod systemd {
    use super::{Backend, ServiceDefinition, ServiceStatus, render_systemd_unit};
    use std::path::PathBuf;
    use std::process::Command;

    /// The `systemd --user` backend: writes
    /// `~/.config/systemd/user/<label>.service` and drives it with
    /// `systemctl --user` (DR-0019 §1).
    pub struct SystemdBackend;

    impl SystemdBackend {
        fn unit_name(label: &str) -> String {
            if label.ends_with(".service") {
                label.to_string()
            } else {
                format!("{label}.service")
            }
        }

        fn unit_path(label: &str) -> PathBuf {
            let base = std::env::var_os("XDG_CONFIG_HOME")
                .map(PathBuf::from)
                .filter(|p| !p.as_os_str().is_empty())
                .unwrap_or_else(|| {
                    let home = std::env::var_os("HOME")
                        .map(PathBuf::from)
                        .unwrap_or_default();
                    home.join(".config")
                });
            base.join("systemd/user").join(Self::unit_name(label))
        }
    }

    impl Backend for SystemdBackend {
        fn definition_path(&self, label: &str) -> PathBuf {
            Self::unit_path(label)
        }

        fn render_definition(&self, def: &ServiceDefinition) -> String {
            render_systemd_unit(def)
        }

        fn register(&self, def: &ServiceDefinition) -> Result<(), String> {
            let path = Self::unit_path(&def.label);
            if let Some(parent) = path.parent() {
                std::fs::create_dir_all(parent)
                    .map_err(|e| format!("cannot create {}: {e}", parent.display()))?;
            }
            std::fs::write(&path, render_systemd_unit(def))
                .map_err(|e| format!("cannot write {}: {e}", path.display()))?;

            let unit = Self::unit_name(&def.label);
            run_systemctl(&["daemon-reload"])?;
            // `enable --now` installs the WantedBy symlink and starts it; for an
            // existing registration this updates and (re)starts it (idempotent).
            run_systemctl(&["enable", "--now", &unit])?;
            Ok(())
        }

        fn unregister(&self, label: &str) -> Result<(), String> {
            let unit = Self::unit_name(label);
            // Best-effort stop + disable (a not-loaded unit is not fatal here);
            // `output()` keeps the "unit not loaded" noise off the terminal.
            let _ = Command::new("systemctl")
                .args(["--user", "disable", "--now", &unit])
                .output();
            let path = Self::unit_path(label);
            let removed = match std::fs::remove_file(&path) {
                Ok(()) => true,
                Err(e) if e.kind() == std::io::ErrorKind::NotFound => false,
                Err(e) => return Err(format!("cannot remove {}: {e}", path.display())),
            };
            if removed {
                let _ = Command::new("systemctl")
                    .args(["--user", "daemon-reload"])
                    .output();
            }
            Ok(())
        }

        fn status(&self, label: &str) -> Result<ServiceStatus, String> {
            let path = Self::unit_path(label);
            let registered = path.is_file();
            let unit = Self::unit_name(label);
            let active = Command::new("systemctl")
                .args(["--user", "is-active", &unit])
                .output()
                .map_err(|e| format!("failed to run systemctl is-active: {e}"))?;
            let running = String::from_utf8_lossy(&active.stdout).trim() == "active";
            let pid = if running {
                let show = Command::new("systemctl")
                    .args(["--user", "show", "-p", "MainPID", "--value", &unit])
                    .output()
                    .map_err(|e| format!("failed to run systemctl show: {e}"))?;
                String::from_utf8_lossy(&show.stdout)
                    .trim()
                    .parse::<u32>()
                    .ok()
                    .filter(|p| *p != 0)
            } else {
                None
            };
            Ok(ServiceStatus {
                registered,
                running,
                pid,
                definition_path: path,
            })
        }
    }

    /// Run `systemctl --user <args>`, mapping a non-zero exit to an error.
    fn run_systemctl(args: &[&str]) -> Result<(), String> {
        let mut cmd = Command::new("systemctl");
        cmd.arg("--user");
        cmd.args(args);
        let out = cmd
            .output()
            .map_err(|e| format!("failed to run systemctl {}: {e}", args.join(" ")))?;
        if !out.status.success() {
            return Err(format!(
                "systemctl --user {} failed: {}",
                args.join(" "),
                String::from_utf8_lossy(&out.stderr).trim()
            ));
        }
        Ok(())
    }
}

/// Check whether the systemd user instance has lingering enabled (DR-0019 §3).
///
/// Without lingering, `systemd --user` services stop at logout — wrong for a
/// long-lived agent. Returns `Some(true/false)` from `loginctl
/// show-user --property=Linger`, or `None` if it cannot be determined (loginctl
/// absent / errored). Pure parsing in [`parse_linger`] for testability.
#[cfg(target_os = "linux")]
pub fn linger_enabled() -> Option<bool> {
    let uid = unsafe { libc::getuid() };
    let out = std::process::Command::new("loginctl")
        .args(["show-user", &uid.to_string(), "--property=Linger"])
        .output()
        .ok()?;
    if !out.status.success() {
        return None;
    }
    parse_linger(&String::from_utf8_lossy(&out.stdout))
}

/// Parse `loginctl show-user --property=Linger` output (`Linger=yes|no`).
#[cfg(any(target_os = "linux", test))]
pub fn parse_linger(text: &str) -> Option<bool> {
    for line in text.lines() {
        if let Some(v) = line.trim().strip_prefix("Linger=") {
            return match v.trim() {
                "yes" => Some(true),
                "no" => Some(false),
                _ => None,
            };
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_def() -> ServiceDefinition {
        ServiceDefinition::for_daemon(
            "/opt/cache-warden/bin/cache-warden",
            "com.github.kawaz.cache-warden",
            Some("/tmp/cw.sock"),
            Some("/home/k/.config/cache-warden/config.toml"),
            Some("/home/k/Library/Logs/cache-warden/daemon.log".to_string()),
        )
    }

    // ---- ServiceDefinition::for_daemon ----

    #[test]
    fn for_daemon_builds_program_args_with_socket() {
        let d = sample_def();
        assert_eq!(
            d.program_args,
            vec![
                "/opt/cache-warden/bin/cache-warden",
                "daemon",
                "run",
                "--socket",
                "/tmp/cw.sock"
            ]
        );
    }

    #[test]
    fn for_daemon_without_socket_omits_socket_args() {
        let d = ServiceDefinition::for_daemon("/bin/cw", "L", None, None, None);
        assert_eq!(d.program_args, vec!["/bin/cw", "daemon", "run"]);
        // No config → only PATH is baked in.
        assert_eq!(d.env.keys().collect::<Vec<_>>(), vec!["PATH"]);
    }

    #[test]
    fn for_daemon_bakes_config_when_present() {
        let d = sample_def();
        assert_eq!(
            d.env.get("CACHE_WARDEN_CONFIG").map(String::as_str),
            Some("/home/k/.config/cache-warden/config.toml")
        );
        assert!(d.env.contains_key("PATH"));
    }

    // ---- launchd plist golden ----

    #[test]
    fn launchd_plist_golden() {
        let d = ServiceDefinition::for_daemon(
            "/opt/bin/cache-warden",
            "com.github.kawaz.cache-warden",
            Some("/tmp/cw.sock"),
            Some("/home/k/.config/cache-warden/config.toml"),
            Some("/home/k/Library/Logs/cache-warden/daemon.log".to_string()),
        );
        let got = render_launchd_plist(&d);
        let expected = "\
<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">
<plist version=\"1.0\">
<dict>
\t<key>Label</key>
\t<string>com.github.kawaz.cache-warden</string>
\t<key>ProgramArguments</key>
\t<array>
\t\t<string>/opt/bin/cache-warden</string>
\t\t<string>daemon</string>
\t\t<string>run</string>
\t\t<string>--socket</string>
\t\t<string>/tmp/cw.sock</string>
\t</array>
\t<key>RunAtLoad</key>
\t<true/>
\t<key>KeepAlive</key>
\t<true/>
\t<key>EnvironmentVariables</key>
\t<dict>
\t\t<key>CACHE_WARDEN_CONFIG</key>
\t\t<string>/home/k/.config/cache-warden/config.toml</string>
\t\t<key>PATH</key>
\t\t<string>/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
\t</dict>
\t<key>StandardOutPath</key>
\t<string>/home/k/Library/Logs/cache-warden/daemon.log</string>
\t<key>StandardErrorPath</key>
\t<string>/home/k/Library/Logs/cache-warden/daemon.log</string>
</dict>
</plist>
";
        assert_eq!(got, expected, "launchd plist golden mismatch");
    }

    #[test]
    fn launchd_plist_escapes_xml_metacharacters() {
        // A label / arg with &, <, > must be entity-escaped so the document
        // stays well-formed.
        let d =
            ServiceDefinition::for_daemon("/bin/cw & co <x>", "a&b<c>", None, Some("v<&>"), None);
        let s = render_launchd_plist(&d);
        assert!(s.contains("<string>a&amp;b&lt;c&gt;</string>"), "{s}");
        assert!(
            s.contains("<string>/bin/cw &amp; co &lt;x&gt;</string>"),
            "{s}"
        );
        assert!(s.contains("<string>v&lt;&amp;&gt;</string>"), "{s}");
        // No raw metacharacter leaked into a value.
        assert!(!s.contains("a&b"), "raw ampersand leaked: {s}");
    }

    #[test]
    fn launchd_plist_without_env_or_log_omits_sections() {
        // for_daemon always bakes PATH, so to test the empty-env branch build
        // the struct directly.
        let d = ServiceDefinition {
            label: "L".into(),
            program_args: vec!["/bin/cw".into(), "daemon".into(), "run".into()],
            env: BTreeMap::new(),
            log_path: None,
        };
        let s = render_launchd_plist(&d);
        assert!(!s.contains("EnvironmentVariables"));
        assert!(!s.contains("StandardOutPath"));
        assert!(s.contains("<key>KeepAlive</key>"));
    }

    // ---- systemd unit golden ----

    #[test]
    fn systemd_unit_golden() {
        let d = ServiceDefinition::for_daemon(
            "/opt/bin/cache-warden",
            "cache-warden",
            Some("/tmp/cw.sock"),
            Some("/home/k/.config/cache-warden/config.toml"),
            None,
        );
        let got = render_systemd_unit(&d);
        let expected = "\
[Unit]
Description=cache-warden secret cache daemon (DR-0019)

[Service]
Type=simple
ExecStart=/opt/bin/cache-warden daemon run --socket /tmp/cw.sock
Restart=on-failure
Environment=\"CACHE_WARDEN_CONFIG=/home/k/.config/cache-warden/config.toml\"
Environment=\"PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin\"

[Install]
WantedBy=default.target
";
        assert_eq!(got, expected, "systemd unit golden mismatch");
    }

    #[test]
    fn systemd_exec_arg_quotes_whitespace_and_quotes() {
        // A path with a space must be quoted so ExecStart does not split it.
        let d = ServiceDefinition {
            label: "L".into(),
            program_args: vec![
                "/opt/my apps/cw".into(),
                "daemon".into(),
                "run".into(),
                "--socket".into(),
                "/tmp/a b.sock".into(),
            ],
            env: BTreeMap::new(),
            log_path: None,
        };
        let s = render_systemd_unit(&d);
        assert!(
            s.contains("ExecStart=\"/opt/my apps/cw\" daemon run --socket \"/tmp/a b.sock\"\n"),
            "{s}"
        );
    }

    #[test]
    fn systemd_env_line_quotes_and_escapes() {
        // A value with a space / quote / backslash survives intact (quoted +
        // escaped).
        assert_eq!(systemd_env_line("K", "a b"), "Environment=\"K=a b\"\n");
        assert_eq!(
            systemd_env_line("K", "a\"b\\c"),
            "Environment=\"K=a\\\"b\\\\c\"\n"
        );
    }

    #[test]
    fn systemd_unit_without_config_has_only_path_env() {
        let d = ServiceDefinition::for_daemon("/bin/cw", "cache-warden", None, None, None);
        let s = render_systemd_unit(&d);
        assert!(s.contains("Environment=\"PATH="));
        assert!(!s.contains("CACHE_WARDEN_CONFIG"));
        assert!(s.contains("ExecStart=/bin/cw daemon run\n"));
    }

    // ---- ServiceStatus render ----

    #[test]
    fn status_render_is_one_screen_table() {
        let st = ServiceStatus {
            registered: true,
            running: true,
            pid: Some(4242),
            definition_path: PathBuf::from("/home/k/Library/LaunchAgents/L.plist"),
        };
        let s = st.render("com.github.kawaz.cache-warden");
        assert!(s.contains("label:      com.github.kawaz.cache-warden"));
        assert!(s.contains("registered: yes"));
        assert!(s.contains("running:    yes"));
        assert!(s.contains("pid:        4242"));
        assert!(s.contains("definition: /home/k/Library/LaunchAgents/L.plist"));
    }

    #[test]
    fn status_render_unregistered_shows_dashes() {
        let st = ServiceStatus {
            registered: false,
            running: false,
            pid: None,
            definition_path: PathBuf::from("/x/L.service"),
        };
        let s = st.render("cache-warden");
        assert!(s.contains("registered: no"));
        assert!(s.contains("running:    no"));
        assert!(s.contains("pid:        -"));
    }

    // ---- launchctl pid parsing ----

    #[test]
    fn parse_launchctl_pid_extracts_pid() {
        let text = "com.github.kawaz.cache-warden = {\n\tactive count = 1\n\tpid = 8821\n\tstate = running\n}";
        assert_eq!(parse_launchctl_pid(text), Some(8821));
    }

    #[test]
    fn parse_launchctl_pid_absent_when_no_pid_line() {
        let text = "com.github.kawaz.cache-warden = {\n\tstate = waiting\n}";
        assert_eq!(parse_launchctl_pid(text), None);
    }

    // ---- linger parsing ----

    #[test]
    fn parse_linger_reads_yes_no() {
        assert_eq!(parse_linger("Linger=yes\n"), Some(true));
        assert_eq!(parse_linger("Linger=no\n"), Some(false));
        assert_eq!(parse_linger("Other=1\n"), None);
    }
}
